version: "3"
services:
  receipt-processor:
    container_name: receipt-processor-compose
    build:
      context: .
      dockerfile: Dockerfile
    image: receipt-processor-compose:latest
    ports:
      - 8080:8080
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-localhost:8000
      - DYNAMO_TABLENAME=receipts
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=secret
      - AWS_REGION=us-east-1
  dynamodb:
    image: amazon/dynamodb-local:1.21.0
    container_name: dynamodb-local-compose
    restart: always
    ports:
      - 8000:8000
    hostname: dynamodb-localhost